// Generated by scripts/generate-quizbun-skill.ts. Do not edit by hand.
// scripts/quizbun-skill-cli.ts
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join as join2, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// src/shared/lib/quiz/import-limits.ts
var MAX_IMPORT_QUESTIONS = 200;
var MAX_IMPORT_BYTES = 1048576;
var LIMIT_PREAMBLE = "This is a Quizbun limit, not a Standard error.";
function formatImportSizeReport(actualBytes) {
  const size = actualBytes === undefined ? "over 1 MB" : formatMegabytes(actualBytes);
  return formatLimitReport({
    path: "root",
    problem: `the Quiz JSON is ${size}; Quizbun imports up to ${formatMegabytes(MAX_IMPORT_BYTES)}`,
    fix: "split the Quiz into smaller Quizzes or shorten long Explanations."
  });
}
function formatImportQuestionCountReport(count) {
  return formatLimitReport({
    path: "questions",
    problem: `${count} Questions; Quizbun imports up to ${MAX_IMPORT_QUESTIONS}`,
    fix: "split the Quiz into two or more Quizzes, for example by subtopic."
  });
}
function checkImportSize(text) {
  if (text.length > MAX_IMPORT_BYTES)
    return formatImportSizeReport(utf8ByteLength(text));
  if (text.length * 3 <= MAX_IMPORT_BYTES)
    return;
  const bytes = utf8ByteLength(text);
  return bytes > MAX_IMPORT_BYTES ? formatImportSizeReport(bytes) : undefined;
}
function checkImportQuestionCount(quiz) {
  if (typeof quiz !== "object" || quiz === null || !("questions" in quiz))
    return;
  const { questions } = quiz;
  if (!Array.isArray(questions) || questions.length <= MAX_IMPORT_QUESTIONS)
    return;
  return formatImportQuestionCountReport(questions.length);
}
function utf8ByteLength(text) {
  return new TextEncoder().encode(text).byteLength;
}
function formatLimitReport(report) {
  return [
    LIMIT_PREAMBLE,
    "",
    `1. Path: \`${report.path}\``,
    `   Problem: ${report.problem}`,
    `   Fix: ${report.fix}`
  ].join(`
`);
}
function formatMegabytes(bytes) {
  const megabytes = bytes / 1048576;
  return `${Number.isInteger(megabytes) ? megabytes : megabytes.toFixed(1)} MB`;
}

// src/shared/lib/quiz-link/quiz-link.ts
var QUIZ_LINK_PARAM = "qos";
var QUIZ_LINK_VERSION = 1;
var MAX_QUIZ_LINK_LENGTH = 1048576;
var BASE64_CHUNK_SIZE = 32768;
async function encodeQuizLink(json) {
  const compressed = await collect(new Blob([new TextEncoder().encode(json)]).stream().pipeThrough(new CompressionStream("deflate")));
  return `${QUIZ_LINK_VERSION}.${toBase64Url(compressed)}`;
}
async function collect(stream) {
  const reader = stream.getReader();
  const chunks = [];
  let total = 0;
  for (;; ) {
    const { done, value } = await reader.read();
    if (done)
      return join(chunks, total);
    chunks.push(value);
    total += value.byteLength;
  }
}
function join(chunks, total) {
  const joined = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    joined.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return joined;
}
function toBase64Url(bytes) {
  let binary = "";
  for (let index = 0;index < bytes.length; index += BASE64_CHUNK_SIZE) {
    binary += String.fromCharCode(...bytes.subarray(index, index + BASE64_CHUNK_SIZE));
  }
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

// scripts/quizbun-skill-cli.ts
var EXIT_INVALID_QUIZ = 1;
var EXIT_OVER_LIMITS = 2;
var EXIT_MISSING_CREATE_QUIZ = 3;
var DEFAULT_BASE = "https://quizbun.fyi/";
var USAGE = `Usage:
  open-quiz <quiz.json> [--out <dir>] [--base <url>] [--print-url]

Options:
  --out <dir>    Directory for the launcher file (default: next to the Quiz file)
  --base <url>   Quizbun site address (default: ${DEFAULT_BASE})
  --print-url    Print the raw link. For scripts only; never paste it into a chat.
  -h, --help     Show this help

Exit codes:
  0  The launcher file was written
  1  The Quiz is invalid; the create-quiz validator's report is printed
  2  The Quiz is over Quizbun's Import limits or the link limit
  3  The create-quiz skill is missing`;
function parseOpenQuizArguments(args) {
  const options = { base: DEFAULT_BASE, help: false, printUrl: false };
  for (let index = 0;index < args.length; index += 1) {
    const arg = args[index] ?? "";
    if (arg === "-h" || arg === "--help")
      options.help = true;
    else if (arg === "--print-url")
      options.printUrl = true;
    else if (arg === "--out" || arg === "--base") {
      const value = args[index + 1];
      if (value === undefined)
        throw new Error(`${arg} needs a value.

${USAGE}`);
      if (arg === "--out")
        options.out = value;
      else
        options.base = value;
      index += 1;
    } else if (arg.startsWith("-")) {
      throw new Error(`Unknown option ${arg}.

${USAGE}`);
    } else if (options.target === undefined) {
      options.target = arg;
    } else {
      throw new Error(`Expected one Quiz file, got more than one.

${USAGE}`);
    }
  }
  return options;
}
function buildQuizUrl(base, payload) {
  const root = base.endsWith("/") ? base : `${base}/`;
  return `${root}import/#${QUIZ_LINK_PARAM}=${payload}`;
}
function escapeHtml(text) {
  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}
function buildLauncherHtml(title, url) {
  const safeTitle = escapeHtml(title);
  const scriptUrl = JSON.stringify(url).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle}</title>
</head>
<body>
<p>Opening <strong>${safeTitle}</strong> in Quizbun.</p>
<p><a href="${escapeHtml(url)}">Open the Quiz in Quizbun</a> if nothing happens.</p>
<noscript><p>JavaScript is off. Use the link above.</p></noscript>
<script>location.replace(${scriptUrl});</script>
</body>
</html>
`;
}
async function main() {
  const options = parseOpenQuizArguments(process.argv.slice(2));
  if (options.help) {
    console.log(USAGE);
    return;
  }
  if (options.target === undefined)
    throw new Error(`Missing the Quiz file.

${USAGE}`);
  const quizPath = resolve(options.target);
  const validatorPath = resolve(dirname(fileURLToPath(import.meta.url)), "../../create-quiz/scripts/validate-quiz.mjs");
  if (!existsSync(validatorPath)) {
    console.error("The quizbun skill needs the create-quiz skill. Install it with `npx skills add a-dev/quizbun --skill create-quiz`.");
    process.exitCode = EXIT_MISSING_CREATE_QUIZ;
    return;
  }
  const validation = spawnSync(process.execPath, [validatorPath, quizPath], { encoding: "utf8" });
  if (validation.status !== 0) {
    process.stdout.write(validation.stdout);
    process.stderr.write(validation.stderr);
    process.exitCode = validation.status ?? EXIT_INVALID_QUIZ;
    return;
  }
  const text = readFileSync(quizPath, "utf8");
  const quiz = JSON.parse(text);
  const limitReport = checkImportSize(text) ?? checkImportQuestionCount(quiz);
  if (limitReport !== undefined) {
    console.error(limitReport);
    process.exitCode = EXIT_OVER_LIMITS;
    return;
  }
  const payload = await encodeQuizLink(JSON.stringify(quiz));
  if (payload.length > MAX_QUIZ_LINK_LENGTH) {
    console.error(`The link would be ${payload.length} characters; browsers open links up to ${MAX_QUIZ_LINK_LENGTH}. Import the \`.json\` file instead.`);
    process.exitCode = EXIT_OVER_LIMITS;
    return;
  }
  const { id, title } = quiz;
  const url = buildQuizUrl(options.base, payload);
  const launcherPath = join2(resolve(options.out ?? dirname(quizPath)), `${id}.open.html`);
  writeFileSync(launcherPath, buildLauncherHtml(title, url));
  console.log(`Wrote ${launcherPath}`);
  if (options.printUrl)
    console.log(url);
}
try {
  await main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = EXIT_INVALID_QUIZ;
}
