import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import type { BunPlugin } from "bun";

const workspaceRoot = process.cwd();
const skillDirectory = resolve(workspaceRoot, "skills/create-quiz");
const checkOnly = process.argv.includes("--check");
const temporaryDirectory = mkdtempSync(join(tmpdir(), "create-quiz-skill-"));

/**
 * The validator reaches the Markdown pipeline through the Public catalog
 * profile's sanitization audit, and that pipeline imports Prism plus seven
 * grammars for the site. Nothing the validator reports depends on syntax
 * highlighting: it asks whether a field renders to anything and whether raw
 * HTML survived, and highlighting only rewrites the inside of a `<pre><code>`
 * block that is non-empty either way.
 *
 * So the skill bundle ships without the highlighter (~57 KB). The stub has an
 * empty `languages` map, which lands `highlightPreCodeBlock` on the branch it
 * already takes for an unlisted fence — un-highlighted by design, not a new
 * code path. `create-quiz-skill-bundle.spec.ts` guards both halves of that.
 */
const stubSyntaxHighlighterPlugin: BunPlugin = {
  name: "stub-prismjs",
  setup(build) {
    build.onResolve({ filter: /^prismjs(\/.*)?$/ }, (args) => ({
      path: args.path,
      namespace: "stub-prismjs",
    }));

    build.onLoad({ filter: /.*/, namespace: "stub-prismjs" }, () => ({
      contents: "export default { highlight: (code) => code, languages: {} };",
      loader: "js",
    }));
  },
};

try {
  const build = await Bun.build({
    entrypoints: [resolve(workspaceRoot, "scripts/create-quiz-validator-cli.ts")],
    format: "esm",
    minify: false,
    naming: "validate-quiz.mjs",
    outdir: temporaryDirectory,
    plugins: [stubSyntaxHighlighterPlugin],
    sourcemap: "none",
    target: "node",
  });

  if (!build.success) {
    const messages = build.logs.map((log) => log.message).join("\n");
    throw new Error(`Could not build the standalone validator:\n${messages}`);
  }

  const bundlePath = resolve(temporaryDirectory, "validate-quiz.mjs");
  const generatedFiles = new Map<string, string>([
    [
      "scripts/validate-quiz.mjs",
      [
        "// Generated by scripts/generate-create-quiz-skill.ts. Do not edit by hand.",
        readFileSync(bundlePath, "utf8"),
      ].join("\n"),
    ],
    [
      "references/quiz.v1.schema.json",
      readFileSync(resolve(workspaceRoot, "public/schema/quiz.v1.json"), "utf8"),
    ],
  ]);

  const driftedFiles: string[] = [];

  for (const [relativePath, expectedContents] of generatedFiles) {
    const destinationPath = resolve(skillDirectory, relativePath);

    if (checkOnly) {
      if (
        !existsSync(destinationPath) ||
        readFileSync(destinationPath, "utf8") !== expectedContents
      ) {
        driftedFiles.push(relative(workspaceRoot, destinationPath));
      }
      continue;
    }

    mkdirSync(dirname(destinationPath), { recursive: true });
    writeFileSync(destinationPath, expectedContents);
  }

  if (driftedFiles.length > 0) {
    throw new Error(
      [
        "The generated create-quiz skill artifacts have drifted:",
        ...driftedFiles.map((filePath) => `- ${filePath}`),
        "Run `bun run skill:create-quiz:generate` and commit the result.",
      ].join("\n"),
    );
  }

  console.log(
    checkOnly
      ? "The generated create-quiz skill artifacts are current."
      : `Generated ${generatedFiles.size} create-quiz skill artifact(s).`,
  );
} finally {
  rmSync(temporaryDirectory, { force: true, recursive: true });
}
