import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";

const workspaceRoot = process.cwd();
const skillDirectory = resolve(workspaceRoot, "skills/quizbun");
const checkOnly = process.argv.includes("--check");
const temporaryDirectory = mkdtempSync(join(tmpdir(), "quizbun-skill-"));

try {
  const build = await Bun.build({
    entrypoints: [resolve(workspaceRoot, "scripts/quizbun-skill-cli.ts")],
    format: "esm",
    minify: false,
    naming: "open-quiz.mjs",
    outdir: temporaryDirectory,
    sourcemap: "none",
    target: "node",
  });

  if (!build.success) {
    const messages = build.logs.map((log) => log.message).join("\n");
    throw new Error(`Could not build the quizbun skill script:\n${messages}`);
  }

  const generatedFiles = new Map<string, string>([
    [
      "scripts/open-quiz.mjs",
      [
        "// Generated by scripts/generate-quizbun-skill.ts. Do not edit by hand.",
        readFileSync(resolve(temporaryDirectory, "open-quiz.mjs"), "utf8"),
      ].join("\n"),
    ],
  ]);

  const driftedFiles: string[] = [];

  for (const [relativePath, expectedContents] of generatedFiles) {
    const destinationPath = resolve(skillDirectory, relativePath);

    if (checkOnly) {
      if (
        !existsSync(destinationPath) ||
        readFileSync(destinationPath, "utf8") !== expectedContents
      ) {
        driftedFiles.push(relative(workspaceRoot, destinationPath));
      }
      continue;
    }

    mkdirSync(dirname(destinationPath), { recursive: true });
    writeFileSync(destinationPath, expectedContents);
  }

  if (driftedFiles.length > 0) {
    throw new Error(
      [
        "The generated quizbun skill artifacts have drifted:",
        ...driftedFiles.map((filePath) => `- ${filePath}`),
        "Run `bun run skill:quizbun:generate` and commit the result.",
      ].join("\n"),
    );
  }

  console.log(
    checkOnly
      ? "The generated quizbun skill artifacts are current."
      : `Generated ${generatedFiles.size} quizbun skill artifact(s).`,
  );
} finally {
  rmSync(temporaryDirectory, { force: true, recursive: true });
}
